jdtrading/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('usuarios/',include('usuarios.urls')),

    path('admin/', admin.site.urls),
 
]

usuarios/urls.py
from django.urls import path
from . import views
app_name = 'usuarios'
urlpatterns = [
    path('', views.index, name="inicio" ),
    path('alumnos', views.alumnos, name="alumnos"),
    path('alumnos_inactivos', views.alumnos_inactivos, name="alumnos_inactivos"),
    path('nuevoalumno', views.nuevo_alumno, name="nuevoalumno"),
    path('guardaralumno',views.guardar_alumno, name="guardaralumno"),
    path('editar_alumno/<int:id>', views.editar_alumno, name='editar_alumno'),
    path('actualizar_alumno', views.actualizar_alumno, name='actualizar_alumno'),
    path('renovar/<int:id>', views.renovar, name='renovar'),
    path('renovar_alumno/<int:id>',views.renovar_alumno, name='renovar_alumno'),
    path('activar_alumno',views.activar_alumno, name='activar_alumno'),
    path('eliminar/<int:id>', views.eliminar, name='eliminar'),

    #Usuarios
    path('nuevo_reporte', views.nuevo_reporte, name='nuevo_reporte'),
    path('guardar_reporte', views.guardar_reporte, name='guardar_reporte'),
    path('reporte_quincenal', views.reporte_quincenal, name='reporte_quincenal'),

]

usuarios/models.py
from django.db import models

# Create your models here.
class Alumnos(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    celular = models.CharField(max_length=15)
    fecha_inicio = models.CharField(max_length=100)
    fecha_fin = models.CharField(max_length=100)
    estado = models.BooleanField(default = True)

class Dia(models.Model):
    fecha = models.CharField(max_length=100)
    estado = models.BooleanField(default=True)
    inversion = models.FloatField(default=0)
    profit = models.FloatField(default=0)
    divisa = models.CharField(max_length=100,default="")
    total = models.FloatField(default=0)



class Noche(models.Model):
    fecha = models.CharField(max_length=100)
    estado = models.BooleanField(default=True)
    inversion = models.FloatField(default=0)
    profit = models.FloatField(default=0)
    divisa = models.CharField(max_length=100, default="")
    total = models.FloatField(default=0)

usuarios/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.urls import reverse
from datetime import datetime, date,timedelta
from django.db.models import Count,Sum
from dateutil.relativedelta import relativedelta

from usuarios.models import Alumnos, Dia, Noche

# Create your views here.
def index(request):
    try:
        return render(request,'usuarios/inicio.html')
    except Exception as e:
        return HttpResponse(e)

def alumnos(request):
    try:
        fecha= date.today()
        dias= timedelta(days=0)
        f= str(fecha+dias)
        print('hola: ', f)
        fechas = Alumnos.objects.filter(fecha_fin__lt=f).update(estado=False)
        print('record: ', fechas)
        a= Alumnos.objects.all()
        for i in a:
            if i.fecha_fin <= f:
                print(i.fecha_fin)
                
        cantidad= a.count()
        
        print(cantidad)
        return render(request,'usuarios/alumnos.html',{'a':a,'c':cantidad})
    except Exception as e:
        return HttpResponse(e)

def nuevo_alumno(request):
    try:
        return render(request,'usuarios/nuevo_alumno.html')
    except Exception as e:
        return HttpResponse(e)

def guardar_alumno(request):
    try:
        fecha_inicio = request.POST['fechaInicio']
        fecha = datetime.strptime(fecha_inicio, '%Y-%m-%d')
        #dias = timedelta(month=request.POST['meses'])
        month = relativedelta(months= int(request.POST['meses']))
        fechaFin= str((fecha + month).date())
        alumno = Alumnos(
            nombre= request.POST['nombre'],
            apellido= request.POST['apellido'],
            celular = request.POST['celular'],
            fecha_inicio = fecha_inicio,
            fecha_fin = fechaFin,
            estado=True
        )
        alumno.save()
                
        return HttpResponseRedirect(reverse('usuarios:alumnos',args=()))
    except Exception as e:
        print(e)
        return HttpResponse(e)
    
def editar_alumno(request,id):
    try:
        a= Alumnos.objects.get(pk=id)        
        
        return render(request,'usuarios/editar_alumno.html',{'a':a})
    except Exception as e:
        return HttpResponse(e)
    
def actualizar_alumno(request):
    try:
        a= Alumnos.objects.get(pk=request.POST['id'])
        a.nombre= request.POST['nombre']
        a.apellido = request.POST['apellido']
        a.celular = request.POST['celular']
        a.fecha_inicio = request.POST['fechaInicio']
        a.fecha_fin = request.POST['fechaFin']
        a.save()
        
        return HttpResponseRedirect(reverse('usuarios:alumnos',args=()))
    except Exception as e:
        return HttpResponse(e)

def renovar(request,id):
    try:
        a = Alumnos.objects.get(pk=id)
        if request.POST['estado']=='si':
            num = int(request.POST['meses'])
            fecha_inicio = a.fecha_fin
            fecha = datetime.strptime(fecha_inicio, '%Y-%m-%d')
            month = relativedelta(months= int(request.POST['meses']))
            fechaFin= str((fecha + month).date())
            a.fecha_inicio = fecha_inicio
            a.fecha_fin = fechaFin
            a.estado = True
            a.save()            
        return HttpResponse('ok')
    except Exception as e:
        return HttpResponse(e)

def alumnos_inactivos(request):
    try:
        a= Alumnos.objects.all().filter(estado=False).values('id','nombre','apellido','celular','fecha_inicio','fecha_fin')

        print(a)
        return render(request,'usuarios/alumnos_inactivos.html',{'a':a})

    except Exception as e:
        return HttpResponse(e)

def renovar_alumno(request,id):
    try:
        alumno = Alumnos.objects.get(pk=id)
        return render(request,'usuarios/renovar_alumno.html',{'a':alumno})
    except Exception as e:
        return HttpResponse(e)

def activar_alumno(request):
    try:
        a= Alumnos.objects.get(pk=request.POST['id'])

        fecha_inicio = request.POST['fecha_inicio']
        fecha = datetime.strptime(fecha_inicio, '%Y-%m-%d')
        month = relativedelta(months= int(request.POST['meses']))
        fechaFin= str((fecha + month).date())
        a.fecha_inicio=fecha_inicio
        a.fecha_fin = fechaFin
        a.estado= True
        a.save()
        return HttpResponseRedirect(reverse('usuarios:alumnos_inactivos',args=()))
    except Exception as e:
        return HttpResponse(e)

def eliminar(request,id):
    try:
        a= Alumnos.objects.get(pk=id)
        a.estado= False
        a.save()
        return HttpResponse('ok')
    except Exception as e:
        return HttpResponse(e)


def nuevo_reporte(request):
    try:
        dia = Dia.objects.all()
        noche= Noche.objects.all()
        return render(request,'usuarios/ingresar_reporte.html',{'dia':dia,'noche':noche})
    except Exception as e:
        return HttpResponse(e)


def guardar_reporte(request):
    try:
        if request.POST['sesion'] == 'dia':
            if request.POST['ope'] == 'ganada':
                profit = float(request.POST['profit'])
                inversion = float(request.POST['inversion'])
                total = (inversion * profit)/100
                
                dia = Dia(
                    fecha = request.POST['fecha'],
                    estado = True,
                    inversion= inversion,
                    profit = profit,
                    divisa = request.POST['divisa'],
                    total = total
                )
                dia.save()
            else:
                profit = float(request.POST['profit'])
                inversion = float(request.POST['inversion'])
                total = (inversion * 100)/100
                dia = Dia(
                    fecha = request.POST['fecha'],
                    estado = False,
                    inversion= inversion,
                    profit = profit,
                    divisa = request.POST['divisa'],
                    total = total
                )
                dia.save()

        else:
            if request.POST['ope'] == 'ganada':
                profit = float(request.POST['profit'])
                inversion = float(request.POST['inversion'])
                total = (inversion * profit)/100
                
                noche = Noche(
                    fecha = request.POST['fecha'],
                    estado = True,
                    inversion= inversion,
                    profit = profit,
                    divisa = request.POST['divisa'],
                    total = total
                )
                noche.save()
            else:
                profit = float(request.POST['profit'])
                inversion = float(request.POST['inversion'])
                total = (inversion * 100)/100                
                noche = Noche(
                    fecha = request.POST['fecha'],
                    estado = False,
                    inversion= inversion,
                    profit = profit,
                    divisa = request.POST['divisa'],
                    total = total
                )
                noche.save()

        return HttpResponseRedirect(reverse('usuarios:nuevo_reporte',args=()))
    except Exception as e:
        return HttpResponse(e)

def reporte_quincenal(request):
    try:
        total_ganadas_dia= Dia.objects.all().filter(estado=True).aggregate(Sum('total'))        
        total_ganadas_noche= Noche.objects.all().filter(estado=True).aggregate(Sum('total'))

        total_perdidas_dia= Dia.objects.all().filter(estado=False).aggregate(Sum('total'))        
        total_perdidas_noche= Noche.objects.all().filter(estado=False).aggregate(Sum('total'))        
        
        total_ganadas = ((float(total_ganadas_dia['total__sum']) + float(total_ganadas_noche['total__sum']))  )
        total_perdidas = ((float(total_perdidas_dia['total__sum'] )+ float(total_perdidas_noche['total__sum']) ))
        print(total_ganadas - total_perdidas)



        total_ganadas_dia = Dia.objects.all().filter(estado=True).count()
        total_ganadas_noche= Noche.objects.all().filter(estado=True).count()
        print(total_ganadas_dia + total_ganadas_noche)

        total_perdidas_dia= Dia.objects.all().filter(estado=False).count()      
        total_perdidas_noche= Noche.objects.all().filter(estado=False).count()
        print(total_perdidas_dia + total_perdidas_noche)

        return HttpResponse('ok')
    except Exception as e:
        return HttpResponse(e)

usuarios/templates/usuarios/alumnos.html
{% extends "usuarios/base.html" %}
{% load static %}

{% block titulo %}JE. TRADER{% endblock titulo %}

{% block body%} <body > {% endblock %}
{% block contenido %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <table class="table table-hover alumnos compact">
                <h3 style="text-align: center;">Alumnos</h3>
                <thead>
                    <td>#</td>
                    <td>Nombre</td>
                    <td>Celular</td>
                    <td>Fecha Ingreso</td>
                    <td>Fecha Expiración</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </thead>
                <tbody>
                    {% for a in a %}
                    {% if a.estado == 1 %}
                    <tr>
                    <td class="item">{{ forloop.counter }}</td>
                    <td class="nombre">{{a.nombre}} {{a.apellido}} </td>
                    <td class="celular">{{a.celular}}</td>
                    <td class="fechaInicio">{{a.fecha_inicio}}</td>
                    <td class="fechaFin">{{a.fecha_fin}}</td>
                    <td>
                        <a onclick="form_edit_alumno('{% url 'usuarios:editar_alumno' a.id %}')" onmouseover="pintar()" data-toggle="modal" data-target=".bd-example-modal-lg"> <i class="fas fa-edit"></i></a>                        
                    </td>
                    <td>
                        <a onclick="eliminar('{% url 'usuarios:eliminar' a.id %}')"> <i class="fas fa-trash-alt"></i></a>                        
                    </td>
                    
                    <td class="d-none">
                        <a  onclick="renovar('{%url 'usuarios:renovar' a.id %}')"><i class="fas fa-retweet"></i>

                        </a>
                    </td>
                </tr>
                    {% endif %}
                    {%endfor%}

                </tbody>
                
            </table>
            <button onclick="formulario_alumno('{% url 'usuarios:nuevoalumno' %}')"data-toggle="modal" data-target=".bd-example-modal-lg" class="btn btn-primary" > Nuevo Alumno</button>
        </div>

    </div>
</div>

<!-- Large modal -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" id="config_alumno">
      ...
    </div>
  </div>
</div>

  

<!--Modal: modalCookie-->
<div class="modal fade top" id="modal_alumno" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true" data-backdrop="true">
  <!-- RENOVAR -->
  <div class="modal-dialog  modal-lg  modal-frame modal-top modal-notify modal-info modal-dialog-centered" role="document">
    <!--Content-->
    <div class="modal-content">
      <!--Body-->
      <div class="modal-body">
        <div class="row d-flex justify-content-center align-items-center">
            <div class="col-4">
                <input type="number"  id="meses" required class="form-control" placeholder="Meses" min="1" max="12">          
            </div>
            <div class="col-4">
                <button class=" btn btn-success" id="renovar">Renovar</button>
            </div>
            <div class="col-4">
                <button class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            </div>
          
        </div>
      </div>
    </div>
    </div>
</div>

    <!--Eliminar-->
<div class="modal fade top" id="modal_eliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true" data-backdrop="true">
  <!-- RENOVAR -->
  <div class="modal-dialog  modal-sm  modal-frame modal-top modal-notify modal-info modal-dialog-centered" role="document">
    <!--Content-->
    <div class="modal-content">
      <!--Body-->
      <div class="modal-body">
        <div class="row d-flex justify-content-center align-items-center">
            <div class="col-4">
                <button class=" btn btn-danger" id="eliminar">Eliminar</button>
            </div>
            <div class="col-4">
                <button class="btn btn-primary" data-dismiss="modal">Cancelar</button>
            </div>
          
        </div>
      </div>
    </div>
    </div>
</div>

  


{% endblock %}

usuarios/templates/usuarios/alumnos_inactivos.html
{% extends "usuarios/base.html" %}
{% load static %}

{% block titulo %}JE. TRADER{% endblock titulo %}

{% block body%} <body > {% endblock %}
{% block contenido %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <table class="table table-hover alumnos compact">
                <h3 style="text-align: center;">Alumnos</h3>
                <thead>
                    <td>#</td>
                    <td>Nombre</td>
                    <td>Celular</td>
                    <td>Fecha Ingreso</td>
                    <td>Fecha Expiración</td>
                    <td></td>
                    <td></td>
                </thead>
                <tbody>
                    {% for a in a %}
                    
                    <tr>
                    <td class="item">{{ forloop.counter }}</td>
                    <td class="nombre">{{a.nombre}} {{a.apellido}} </td>
                    <td class="celular">{{a.celular}}</td>
                    <td class="fechaInicio">{{a.fecha_inicio}}</td>
                    <td class="fechaFin">{{a.fecha_fin}}</td>
                    <td>
                        <a onclick="form_renovar_alumno('{% url 'usuarios:renovar_alumno' a.id %}')" data-toggle="modal" data-target=".bd-example-modal-lg"><i class="fas fa-retweet"></i>

                        </a>                        
                    </td>
                    <td class="d-none"></td>
                </tr>
                    {%endfor%}
                </tbody>
                
            </table>
            <button onclick="formulario_alumno('{% url 'usuarios:nuevoalumno' %}')"data-toggle="modal" data-target=".bd-example-modal-lg" class="btn btn-primary" > Nuevo Alumno</button>
        </div>

    </div>
</div>

<!-- Large modal -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" id="config_alumno">
      ...
    </div>
  </div>
</div>

  

<!--Modal: modalCookie-->
<div class="modal fade top" id="modal_alumno" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true" data-backdrop="true">
  <div class="modal-dialog  modal-lg  modal-frame modal-top modal-notify modal-info modal-dialog-centered" role="document">
    <!--Content-->
    <div class="modal-content">
      <!--Body-->
      <div class="modal-body">
        <div class="row d-flex justify-content-center align-items-center">
            <div class="col-4">
                <input type="number"  id="meses" required class="form-control" placeholder="Meses" min="1" max="12">          
            </div>
            <div class="col-4">
                <button class=" btn btn-success" id="renovar">Renovar</button>
            </div>
            <div class="col-4">
                <button class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            </div>
          
        </div>
      </div>
    </div>
  


{% endblock %}

usuarios/templates/usuarios/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Last-Modified" content="0">
    <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
    <meta http-equiv="Pragma" content="no-cache">

    <link rel="stylesheet" href="{% static 'usuarios/css/bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">

    <link rel="stylesheet" href="{% static 'usuarios/css/all.css'%}">

    



    <title> {% block titulo %} {% endblock %} </title>
</head>

{% block body %} {%endblock%}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">J. E Trader</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Alumnos
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'usuarios:alumnos' %}">Activos</a>
                <a class="dropdown-item" href="{% url 'usuarios:alumnos_inactivos'  %}">Inactivos</a>
                <div class="dropdown-divider"></div>
                
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Resultados
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'usuarios:nuevo_reporte' %}">Insertar</a>
                <a class="dropdown-item" href="{% url 'usuarios:reporte_quincenal'  %}">ReporteQuincenal</a>
                <div class="dropdown-divider"></div>
                
              </div>
            </li>
            
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>


    {% block contenido %}
    
    
    {% endblock %}



    

    <script src="{% static 'usuarios/js/jquery-3.4.1.min.js' %} "></script>
    <script src="{% static 'usuarios/js/popper.min.js' %} "></script>
    <script src="{% static 'usuarios/js/bootstrap.min.js' %} "></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
    <script src="{% static 'usuarios/js/moment.js' %} "></script>
    
  
    <script src="{% static 'usuarios/js/all.js' %} "></script>
    
    


    <script src="{%static 'usuarios/js/main.js' %}"> </script>
</body>

usuarios/templates/usuarios/editar_alumno.html
<div class="container">
    <form action="{% url 'usuarios:actualizar_alumno' %}" method="post">
    {% csrf_token %}
        <div class="form-row">
            <div class="col-6 form-group">
                <label for="exampleInputEmail1">Nombre</label>
                <input type="text" class="form-control" id="exampleInputEmail1" name="nombre" aria-describedby="emailHelp" placeholder=Nombre value="{{a.nombre}}">
            </div>
            <div class="col-6 form-group">
                <label for="exampleInputEmail1">Apellido</label>
                <input type="text" class="form-control" id="exampleInputEmail1" name="apellido" aria-describedby="emailHelp" placeholder="Apellido" value="{{a.apellido}}">
            </div>
        </div>
        <div class="form-row">
            <div class="col-4 form-group">
                <label for="exampleInputEmail1">Celular</label>
                <input type="text" class="form-control" id="exampleInputEmail1" name="celular" aria-describedby="emailHelp" placeholder=Celular value="{{a.celular}}">
            </div>
            <div class="col-4 form-group">
                <label for="exampleInputEmail1">Fecha Ingreso</label>
                <input type="date" class="form-control" id="exampleInputEmail1" name="fechaInicio" aria-describedby="emailHelp" value="{{a.fecha_inicio}}">
            </div>
            <div class="col-4 form-group">
                <label for="exampleInputEmail1">Fecha Fin</label>
                <input type="date" class="form-control" id="exampleInputEmail1" name="fechaFin" aria-describedby="emailHelp"  value="{{a.fecha_fin}}">
                <input type="hidden" name="id" value="{{a.id}}">
            </div>
        </div>
        <div class="form-row">
            
        </div>
        <div class="form-row">
            <div class="col-5 form-group">
                <input type="submit" value="Guardar" class="btn btn-success">
            </div>
        </div>
    </form>
</div>
    

usuarios/templates/usuarios/ingresar_reporte.html
{% extends "usuarios/base.html" %}
{% load static %}

{% block titulo %}Nuevo Reporte{% endblock titulo %}

{% block body%} <body > {% endblock %}
{% block contenido %}

<div class="container-fluid">

    <div class="row">
        <div class="col-6">
            <h3>Nuevo Reporte</h3>
            <hr>
            <form action="{% url 'usuarios:guardar_reporte' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-4">
                        <input type="date" id="fecha" name="fecha" class="form-control">
                    </div>
                    <div class="col-4 mt-2" >
                        <span><input type="radio" id="dia" name="sesion" value="dia">
                        <label for="dia">Día</label></span> <span> <input type="radio" id="noche" name="sesion" value="noche">
                            <label for="noche">Noche</label><br></span>
                    </div>                   
                    
                </div>
                <hr>
                <div class="form-row">
                    <div class="col-3 mt-2">
                            <span><input type="radio" id="ganada" name="ope" value="ganada">
                            <label for="ganada">Ganada</label> </span> <span> <input type="radio" id="perdida" name="ope" value="perdida">
                            <label for="perdida">Perdida</label><br></span>                       
                    </div>
                    <div class="col-3">
                        <input type="text" id="divisa" name="divisa" class="form-control" placeholder="divisa" min="0">    
                    </div>
                    <div class="col-3">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                              <span class="input-group-text">$</span>
                            </div>                            
                            <input type="number" id="inversion" name="inversion" class="form-control" placeholder="Importe" min="0" aria-label="Amount (to the nearest dollar)">                                
                          </div>
                    </div>
                    <div class="col-3">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                              <span class="input-group-text">%</span>
                            </div>                                
                            <input type="number" id="profit" name="profit" class="form-control" placeholder="Profit" min="0" aria-label="Amount (to the nearest dollar)">
                          </div>
                    </div>
                </div>
                <hr>
                <div class="form-row">
                    <div class="col-2">
                    <input type="submit" value="Guardar" class="btn btn-success">                        
                    </div>
                </div>



            </form>
        </div>
    </div>


<div class="row">

    <div class="col-6">
        <h4 style="text-align: center; color: green;">Sesion Día</h4>
        <table class="table">
                <thead>
                    <th>Fecha </th>
                    <th>Divisa </th>
                    <th>Importe</th>
                    <th>Profit</th>
                    <th>Estado</th>
                    <th>Total </th>
                </thead>
                {% for dia in dia %}
                <tbody>
                    <tr {% if dia.estado  %} class="bg-success"{% else %} class="bg-danger"{% endif %} style="color: white;">
                        <td>{{dia.fecha}}</td>
                        <td>{{dia.divisa}}</td>
                        <td>{{dia.inversion}}</td>
                        <td>{{dia.profit}}</td>
                        <td> {% if dia.estado  %} Ganada {% else %} perdida {%endif%} </td>
                        <td>{{dia.total}}</td>
                    </tr>
                </tbody>
                {%endfor%}
            </table>
            
        </div>


        <div class="col-6">
            <h4 style="text-align: center; color: green;">Sesion Noche</h4>
            <table class="table">
                <thead>
                    <th>Fecha </th>
                    <th>Divisa </th>
                    <th>Importe</th>
                    <th>Profit</th>
                    <th>Estado</th>
                    <th>Total </th>
                </thead>
                <tbody>
                    {% for noche in noche %}
                    <tr {% if noche.estado  %} class="bg-success"{% else %} class="bg-danger"{% endif %} style="color: white;">
                        <td>{{noche.fecha}}</td>
                        <td>{{noche.divisa}}</td>
                        <td>{{noche.inversion}}</td>
                        <td>{{noche.profit}}</td>
                        <td>{% if noche.estado %} Ganada {% else %} Perdida {%endif%}</td>
                        <td>{{noche.total}}</td>
                        {%endfor%}
                    </tr>
                </tbody>
            </table>            
        </div>

    </div>

</div>




{% endblock %}

usuarios/templates/usuarios/inicio.html
{% extends "usuarios/base.html" %}
{% load static %}

{% block titulo %}J E. TRADER{% endblock titulo %}
{% block body %} <body> {% endblock %}
    
    {% block contenido %}
{% endblock %}

usuarios/templates/usuarios/nuevo_alumno.html
    <div class="container">
        <form action="{% url 'usuarios:guardaralumno' %}" method="post">
        {% csrf_token %}
            <div class="form-row">
                <div class="col-6 form-group mt-2">
                    <label for="exampleInputEmail1"></label>
                    <input type="text" class="form-control" id="exampleInputEmail1" name="nombre" aria-describedby="emailHelp" placeholder=Nombre>
                </div>
                <div class="col-6 form-group mt-2" >
                    <label for="exampleInputEmail1"></label>
                    <input type="text" class="form-control" id="exampleInputEmail1" name="apellido" aria-describedby="emailHelp" placeholder="Apellido">
                </div>
            </div>
            <div class="form-row">
                <div class="col-5 form-group mt-2">
                    <label for="exampleInputEmail1 "></label>
                    <input type="text" class="form-control" id="exampleInputEmail1" name="celular" aria-describedby="emailHelp" placeholder=Celular>
                </div>
                <div class="col-5 form-group" style="text-align: center;">
                    <label for="exampleInputEmail1">Fecha Ingreso</label>
                    <input type="date" class="form-control" id="exampleInputEmail1" name="fechaInicio" aria-describedby="emailHelp">
                </div>
                <div class="col-2 form-group mt-2" >
                    <label for="exampleInputEmail1"></label>
                    <input type="number" class="form-control" id="exampleInputEmail1" name="meses" aria-describedby="emailHelp" placeholder="Meses" min="1" max="12">
                </div>
            </div>
            <div class="form-row">
                
            </div>
            <div class="form-row">
                <div class="col-5 form-group">
                    <input type="submit" value="Guardar" class="btn btn-success">
                </div>
            </div>
        </form>
    </div>
        